# Generated by Django 4.0.3 on 2022-04-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camping',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='camping',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='YYYY-MM-DD')),
                ('end_date', models.DateField(default='YYYY-MM-DD')),
                ('people_number', models.PositiveIntegerField(verbose_name='number of people')),
                ('is_reserved', models.BooleanField(default=False)),
                ('camping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='campings.camping')),
            ],
        ),
    ]
