# Generated by Django 4.0.3 on 2022-04-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campings', '0003_rename_camp_type_camping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date',
            new_name='check_out',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_reserved',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='people_number',
            field=models.PositiveSmallIntegerField(verbose_name='Guests'),
        ),
    ]
